# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'SampleEventBrowser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'EventBrowser', :path => '../EventBrowser.podspec', :subspecs => [
  'EventBrowserUI'
  ]
  
  target 'SampleEventBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'EventBrowser'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0' # Set to your app’s deployment target
      end
    end
  end
end
